# Generated by Django 4.2.3 on 2023-07-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="canteen_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canteen_name", models.CharField(max_length=200)),
                ("cmail_id", models.CharField(max_length=200)),
                ("ccontact_no", models.CharField(max_length=12)),
                ("caddress", models.CharField(max_length=200)),
                ("clocation", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="food_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=200)),
                ("food_rate", models.CharField(max_length=200)),
                ("food_image", models.ImageField(default="", upload_to="images/")),
                (
                    "canteen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.canteen_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_fullname", models.CharField(max_length=200)),
                ("user_emailid", models.CharField(max_length=200)),
                ("user_contactnumber", models.CharField(max_length=200)),
                ("pwd", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="food_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=200)),
                (
                    "canteen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.canteen_details",
                    ),
                ),
                (
                    "food_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.food_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ctransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_quantity", models.CharField(max_length=200)),
                ("date", models.CharField(max_length=200)),
                ("total", models.IntegerField(editable=False)),
                (
                    "canteen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.canteen_details",
                    ),
                ),
                (
                    "food_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canteen.food_details",
                    ),
                ),
            ],
        ),
    ]
