# Generated by Django 4.2.3 on 2023-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0002_alter_food_details_food_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctransaction",
            name="food_quantity",
            field=models.IntegerField(max_length=200),
        ),
    ]
