# Generated by Django 4.2.3 on 2023-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0004_alter_ctransaction_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctransaction",
            name="total",
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
