# Generated by Django 4.2.3 on 2023-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0005_alter_ctransaction_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctransaction",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
