# Generated by Django 4.2.3 on 2023-08-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_alter_ctransaction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
